---
- hosts: all
  become: yes
  tasks:
        - name: i want to install tree
          apt:
              name: tree
              state: absent
        - name: i want to install wget
          apt: 
              name: wget
              state: absent      